---
kind: pipeline
name: default

steps:
    - name: scan-build
      image: debian:buster
      pull: always
      commands:
      - apt-get update && apt-get install -yq build-essential autotools-dev lsb-release pkg-config automake autoconf libtool-bin clang-tools-7
      - apt-get install -yq cmake uuid-dev libssl-dev
      - sed -i '/cotire/d' ./CMakeLists.txt
      - mkdir -p scan-build
      - scan-build-7 -o ./scan-build/ cmake .
      - echo '#!/bin/bash\nscan-build-7 -o ./scan-build/ make -j`nproc --all` |& tee ./scan-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > ./scan-build-status.txt\n' > scan.sh
      - chmod +x scan.sh
      - ./scan.sh
      - exitstatus=`cat ./scan-build-status.txt`
      - echo "*** Exit status is $exitstatus"

    - name: notify
      image: signalwire/drone-notify
      pull: always
      environment:
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
        ENV_FILE:
          from_secret: notify_env
      commands:
      - /root/scan-build-notify.sh
      
trigger:
  branch:
  - master
  - v2.0

trigger:
  event:
  - pull_request
  - push
---
kind: signature
hmac: 96251971feba4ff8bb30573bcd845888415184077f3c5f53b2a7ec2fafbe3830

...
